### ISSUE TITLE
ecmcEcSlave.template doesn't exist in few substitutions files. 

### ISSUE THREAD

**Issue by jeonghanlee** [icshwi/ecmccfg#4]
Hi @anderssandstrom ,

 While I update subsititutions and template files, I saw two substitutions files (`ecmcEL3104` and `ecmEL7332`) do not have `ecmcEcSlave.template` such as

```
file "ecmcEcSlave.template"
{
  pattern {}
          {}
}
```

Is it normal?

**Comment by anderssandstrom** [comment]
@jeonghanlee, No its not normal. These files should contain the ecmcEcSlave.tempalte file aswell.
I will add.

**Comment by anderssandstrom** [comment]
Done!
